### PR TITLE
Add TF-IDF weights to tokens

### PR DESCRIPTION
**Pull request by micheleriva**
This PR is still a work in progress. The algorithms are just POCs and highly inefficient, once we validate the idea, I'll proceed to optimize them.

### CODE REVIEW

**Comment by thomscoder** [comment]
Heyy, this is pretty neat! 💯 
Especially for multi word searches.

I really like the idea.

<hr>

Will it be in symbiosis with `tolerance` ?

**Comment by micheleriva** [comment]
It shouldn't affect how typo tolerance work, but I really need to optimize this before trying 😄

**Comment by thomscoder** [comment]
I guessed, i really like the idea 😄

**Comment by micheleriva** [comment]
Closing this PR in favor of this Lyra plugin: https://github.com/LyraSearch/plugin-token-relevance

**Pull request closed without merging**
