### PR TITLE
Store defaultLanguage

### PR DESCRIPTION
**Pull request by YusufCelik**
The defaultLanguage param is not being saved. As such, when you restore a file from disk that used the Arabic indexer, searches won't work as they default to English. See the second pull request I opened for the data persistence plugin (https://github.com/LyraSearch/plugin-data-persistence/pull/11). Both these changes are needed for the search to work again after a file gets restored.

### CODE REVIEW

**Comment by ShogunPanda** [comment]
Can you please add the loading of the parameter in the `load` function? The rest LGTM!

**Comment by micheleriva** [comment]
@YusufCelik thanks for your contribution, would you mind adding a test for this?

**Comment by ShogunPanda** [comment]
> @YusufCelik thanks for your contribution, would you mind adding a test for this?

Thanks. I meant to write it and forgot about it XD

**Comment by YusufCelik** [comment]
Thanks. Will do. I do have a question about the present merge conflict: what is up with the main and recent release tag differences? There is no lyra.nodes. Which one is outdated? (I based my changes on the recent release tag).

**Comment by ShogunPanda** [comment]
I'm not sure about it, but I would say to always rebase and branch out against `main`.

**Comment by micheleriva** [comment]
Hi @YusufCelik ,
we're planning a release for this week, is there something we can do to get this one merged?

Thanks again!

**Comment by micheleriva** [comment]
Closing this, implemented and co-authored in a different commit

**Pull request closed without merging**
